<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Threading.Tasks.Dataflow" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
  </ItemGroup>

</Project>

